### ISSUE TITLE
Investigate failure if an artifact is already uploaded in the `Staging` ring

### ISSUE THREAD

**Issue by MilenaHristova** [dotnet/arcade-services#2738]
The `Publish release artifacts` step in the staging pipeline fails on rerun because the `release` artifact is already uploaded for the build
Log: https://dev.azure.com/dnceng/internal/_build/results?buildId=2212903&view=logs&j=bdcf6bb7-6b13-5f8a-15bc-62191d8e11cf&t=b64ec7e5-6f1b-5ddd-2bc7-95675b50b944
Previous attempt: https://dev.azure.com/dnceng/internal/_build/results?buildId=2212903&view=logs&j=96f25be6-9c31-54f9-b939-1779b950b360&t=01c86e67-0f2d-5d2c-1d75-ed312cf9fc42&s=58b6074f-2ff4-5217-6d0a-6ea18a1fee5c

The failure blocks the execution of the following job (`Initial Creation of .NET Core Release Manifest File`). We should consider configuring the job to continue on error in that case so that all jobs can be rerun

**Comment by mmitche** [comment]
Agreed. If the artifact was different on the rerun (e.g. maybe it failed to upload part of the way first time), than it would require us to rerun the entire pipeline. But that seems less likely.

**Comment by andriipatsula** [comment]
Suggest adding a condition to:
```
- powershell: |
     // check if already published and set the releaseArtifactsPublished variable
  displayName: Set Variables

- task: PublishPipelineArtifact@1
  displayName: Publish release artifacts
  inputs:
    targetPath: $(Build.ArtifactStagingDirectory)\release
    artifactName: release
    parallel: true
 condition: eq(variables['releaseArtifactsPublished'], 'true')
```
