### ISSUE TITLE
Templates for assetless build promotion should be simplified

### ISSUE THREAD

**Issue by premun** [dotnet/arcade-services#4706]
Currently, the minimal set of parameters is this:

```yaml
parameters:
  artifacts:
    publish:
      manifests: true
  isAssetlessBuild: true
  publishAssetsImmediately: true
```

It should be this:

```yaml
parameters:
  isAssetlessBuild: true
```

This is mostly about some if/else statements in YAML that skip the build promotion.
`publishAssetsImmediately` should be set to `true`.
